services:
  backend:
    build: .
    container_name: dynecron_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - dynecron_network

networks:
  dynecron_network:
    external: true
    name: dynecron_network